export const ACTIONS = {
  REQUEST_SOURCE_METADATA: 'REQUEST_SOURCE_METADATA',
  RECEIVE_SOURCE_METADATA: 'RECEIVE_SOURCE_METADATA',
  REQUEST_SOURCE_METADATA_FAILED: 'REQUEST_SOURCE_METADATA_FAILED',

  REQUEST_SOURCE_METADATA_DELETE: 'REQUEST_SOURCE_METADATA_DELETE',
  REQUEST_SOURCE_METADATA_DELETE_FAILED: 'REQUEST_SOURCE_METADATA_DELETE_FAILED',
  REQUEST_SOURCE_METADATA_DELETED: 'REQUEST_SOURCE_METADATA_DELETED'
};
