export const ACTIONS = {
  REQUEST_SOURCE_THUMBS: 'REQUEST_SOURCE_THUMBS',
  RECEIVE_SOURCE_THUMBS: 'RECEIVE_SOURCE_THUMBS',
  REQUEST_SOURCE_THUMBS_FAILED: 'REQUEST_SOURCE_THUMBS_FAILED',

  GENERATE_SOURCE_THUMB: 'GENERATE_SOURCE_THUMB',
  SOURCE_THUMB_GENERATED: 'SOURCE_THUMB_GENERATED',
  GENERATE_SOURCE_THUMB_FAILED: 'GENERATE_SOURCE_THUMB_FAILED'
};
