# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "packages/lens-app/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: yarn install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/lens-app/node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "packages/lens-app/package.json" }}

      - run:
          name: yarn build
          command: yarn build

      - run:
          name: yarn test
          command: yarn test

workflows:
  version: 2
  build-prod:
    jobs:
      - build:
          filters:
            branches:
              only: deployment
