export const ACTIONS = {
  SERVICE_CONNECT: 'SERVICE_CONNECT',
  SERVICE_CONNECTED: 'SERVICE_CONNECTED',
  SERVICE_FAILED: 'SERVICE_FAILED',
  SEND_SERVICE_MESSAGE: 'SEND_SERVICE_MESSAGE',
  RECEIVE_SERVICE_MESSAGE: 'RECEIVE_SERVICE_MESSAGE'
};
