import { createActions } from 'redux-actions';

export const EDITOR_ACTIONS_PREFIX_SIMULATION_DATA = 'editor-simulation-data';
export const {
  requestSimulationsForSource,
  receiveSimulationsForSource,
  requestSimulationsForSourceFailed,
  requestHikes,
  receiveHikes,
  requestHikesFailed,
  saveSimulation,
  saveSimulationSucceeded,
  saveSimulationFailed,
  saveNewSimulation,
  saveNewSimulationSucceeded,
  saveNewSimulationFailed,
  deleteSimulation,
  deleteSimulationSucceeded,
  deleteSimulationFailed,
  saveHikes,
  saveHikesSucceeded,
  saveHikesFailed,
} = createActions(
  'REQUEST_SIMULATIONS_FOR_SOURCE',
  'RECEIVE_SIMULATIONS_FOR_SOURCE',
  'REQUEST_SIMULATIONS_FOR_SOURCE_FAILED',
  'REQUEST_HIKES',
  'RECEIVE_HIKES',
  'REQUEST_HIKES_FAILED',
  'SAVE_SIMULATION',
  'SAVE_SIMULATION_SUCCEEDED',
  'SAVE_SIMULATION_FAILED',
  'SAVE_NEW_SIMULATION',
  'SAVE_NEW_SIMULATION_SUCCEEDED',
  'SAVE_NEW_SIMULATION_FAILED',
  'DELETE_SIMULATION',
  'DELETE_SIMULATION_SUCCEEDED',
  'DELETE_SIMULATION_FAILED',
  'SAVE_HIKES',
  'SAVE_HIKES_SUCCEEDED',
  'SAVE_HIKES_FAILED',
  {
    prefix: EDITOR_ACTIONS_PREFIX_SIMULATION_DATA,
  },
);
