import { createActions } from 'redux-actions';

export const EDITOR_ACTIONS_PREFIX_SIMULATION_DATA = 'editor-simulation-data';
export const {
  requestSimulationsForSource,
  receiveSimulationsForSource,
  requestSimulationsForSourceFailed,
  requestHikes,
  receiveHikes,
  requestHikesFailed,
  // simulations
  saveSimulation,
  saveSimulationSucceeded,
  saveSimulationFailed,
  saveNewSimulation,
  saveNewSimulationSucceeded,
  saveNewSimulationFailed,
  deleteSimulation,
  deleteSimulationSucceeded,
  deleteSimulationFailed,
  // simulation hikes
  saveHikes,
  saveHikesSucceeded,
  saveHikesFailed,
  // executions
  saveExecution,
  saveExecutionSucceeded,
  saveExecutionFailed,
  saveNewExecution,
  saveNewExecutionSucceeded,
  saveNewExecutionFailed,
  deleteExecution,
  deleteExecutionSucceeded,
  deleteExecutionFailed,
  runExecution,
  runExecutionSucceeded,
  runExecutionFailed,
  // rendering
  saveRendering,
  saveRenderingSucceeded,
  saveRenderingFailed,
  saveNewRendering,
  saveNewRenderingSucceeded,
  saveNewRenderingFailed,
  deleteRendering,
  deleteRenderingSucceeded,
  deleteRenderingFailed,
} = createActions(
  'REQUEST_SIMULATIONS_FOR_SOURCE',
  'RECEIVE_SIMULATIONS_FOR_SOURCE',
  'REQUEST_SIMULATIONS_FOR_SOURCE_FAILED',
  'REQUEST_HIKES',
  'RECEIVE_HIKES',
  'REQUEST_HIKES_FAILED',
  // simulations
  'SAVE_SIMULATION',
  'SAVE_SIMULATION_SUCCEEDED',
  'SAVE_SIMULATION_FAILED',
  'SAVE_NEW_SIMULATION',
  'SAVE_NEW_SIMULATION_SUCCEEDED',
  'SAVE_NEW_SIMULATION_FAILED',
  'DELETE_SIMULATION',
  'DELETE_SIMULATION_SUCCEEDED',
  'DELETE_SIMULATION_FAILED',
  // simulation hikes
  'SAVE_HIKES',
  'SAVE_HIKES_SUCCEEDED',
  'SAVE_HIKES_FAILED',
  // executions
  'SAVE_EXECUTION',
  'SAVE_EXECUTION_SUCCEEDED',
  'SAVE_EXECUTION_FAILED',
  'SAVE_NEW_EXECUTION',
  'SAVE_NEW_EXECUTION_SUCCEEDED',
  'SAVE_NEW_EXECUTION_FAILED',
  'DELETE_EXECUTION',
  'DELETE_EXECUTION_SUCCEEDED',
  'DELETE_EXECUTION_FAILED',
  'RUN_EXECUTION',
  'RUN_EXECUTION_SUCCEEDED',
  'RUN_EXECUTION_FAILED',
  // renderings
  'SAVE_RENDERING',
  'SAVE_RENDERING_SUCCEEDED',
  'SAVE_RENDERING_FAILED',
  'SAVE_NEW_RENDERING',
  'SAVE_NEW_RENDERING_SUCCEEDED',
  'SAVE_NEW_RENDERING_FAILED',
  'DELETE_RENDERING',
  'DELETE_RENDERING_SUCCEEDED',
  'DELETE_RENDERING_FAILED',
  {
    prefix: EDITOR_ACTIONS_PREFIX_SIMULATION_DATA,
  },
);
