import { createActions } from 'redux-actions';

export const {
  changeSimulation,
  changeHike,
  changeHikeList,
  changeTrail,
  changeTrailList,
  changeHiker,
  changeHikerList,
} = createActions(
  'CHANGE_SIMULATION',
  'CHANGE_HIKE',
  'CHANGE_HIKE_LIST',
  'CHANGE_TRAIL',
  'CHANGE_TRAIL_LIST',
  'CHANGE_HIKER',
  'CHANGE_HIKER_LIST',
  {
    prefix: 'editor-sagas',
  },
);

export const {
  setSimulation,
  updateSimulation,
  addHike,
  updateHike,
  updateHikes,
  addTrail,
  updateTrail,
  updateTrails,
  addHiker,
  updateHiker,
  updateHikers,
  requestSimulationsForSource,
  receiveSimulationsForSource,
  requestSimulationsForSourceFailed,
  requestHikes,
  receiveHikes,
  requestHikesFailed,
  setActiveScope,
  ensureEditorTitle,
  editorActionEnabled,
  editorActionDisabled,
  editorActionValid,
  editorActionInvalid,
} = createActions(
  'SET_SIMULATION',
  'UPDATE_SIMULATION',
  'ADD_HIKE',
  'UPDATE_HIKE',
  'UPDATE_HIKES',
  'ADD_TRAIL',
  'UPDATE_TRAIL',
  'UPDATE_TRAILS',
  'ADD_HIKER',
  'UPDATE_HIKER',
  'UPDATE_HIKERS',
  'REQUEST_SIMULATIONS_FOR_SOURCE',
  'RECEIVE_SIMULATIONS_FOR_SOURCE',
  'REQUEST_SIMULATIONS_FOR_SOURCE_FAILED',
  'REQUEST_HIKES',
  'RECEIVE_HIKES',
  'REQUEST_HIKES_FAILED',
  'SET_ACTIVE_SCOPE',
  'ENSURE_EDITOR_TITLE',
  'EDITOR_ACTION_ENABLED',
  'EDITOR_ACTION_DISABLED',
  'EDITOR_ACTION_VALID',
  'EDITOR_ACTION_INVALID',
  {
    prefix: 'editor',
  },
);
