// constants
export const ACTIONS = {
  REQUEST_SIMULATIONS_FOR_SOURCE: 'REQUEST_SIMULATIONS_FOR_SOURCE',
  RECEIVE_SIMULATIONS_FOR_SOURCE: 'RECEIVE_SIMULATIONS_FOR_SOURCE',
  REQUEST_SIMULATIONS_FOR_SOURCE_FAILED: 'REQUEST_SIMULATIONS_FOR_SOURCE_FAILED',

  SET_FORM: 'SET_FORM', // set form values from hierarchy element
  UPDATE_FORM: 'UPDATE_FORM', // apply changes to form

  SAVE_SIMULATION: 'SAVE_SIMULATION',
  SAVE_SIMULATION_SUCCEEDED: 'SAVE_SIMULATION_SUCCEEDED',
  SAVE_SIMULATION_FAILED: 'SAVE_SIMULATION_FAILED',

  SAVE_EXECUTION: 'SAVE_EXECUTION',
  SAVE_EXECUTION_SUCCEEDED: 'SAVE_EXECUTION_SUCCEEDED',
  SAVE_EXECUTION_FAILED: 'SAVE_EXECUTION_FAILED',

  SAVE_RENDERING: 'SAVE_RENDERING',
  SAVE_RENDERING_SUCCEEDED: 'SAVE_RENDERING_SUCCEEDED',
  SAVE_RENDERING_FAILED: 'SAVE_RENDERING_FAILED',

  EDITOR_ACTION_ENABLED: 'EDITOR_ACTION_ENABLED',
  EDITOR_ACTION_DISABLED: 'EDITOR_ACTION_DISABLED',

  EDITOR_ACTION_VALID: 'EDITOR_ACTION_VALID',
  EDITOR_ACTION_INVALID: 'EDITOR_ACTION_INVALID',

  // editor is working on simulation, execution, or rendering
  SET_ACTIVE_SCOPE: 'SET_ACTIVE_SCOPE',

  ENSURE_EDITOR_TITLE: 'ENSURE_EDITOR_TITLE',
};
