// constants
export const ACTIONS = {
  REQUEST_SIMULATIONS_FOR_SOURCE: 'REQUEST_SIMULATIONS_FOR_SOURCE',
  RECEIVE_SIMULATIONS_FOR_SOURCE: 'RECEIVE_SIMULATIONS_FOR_SOURCE',
  REQUEST_SIMULATIONS_FOR_SOURCE_FAILED: 'REQUEST_SIMULATIONS_FOR_SOURCE_FAILED',

  LOAD_SIMULATION: 'LOAD_SIMULATION',
  SET_SIMULATION: 'SET_SIMULATION',
  UPDATE_SIMULATION: 'UPDATE_SIMULATION',

  SAVE_SIMULATION: 'SAVE_SIMULATION',
  SAVE_SIMULATION_SUCCEEDED: 'SAVE_SIMULATION_SUCCEEDED',
  SAVE_SIMULATION_FAILED: 'SAVE_SIMULATION_FAILED',

  LOAD_EXECUTION: 'LOAD_EXECUTION',
  SET_EXECUTION: 'SET_EXECUTION',
  UPDATE_EXECUTION: 'UPDATE_EXECUTION',

  SAVE_EXECUTION: 'SAVE_EXECUTION',
  SAVE_EXECUTION_SUCCEEDED: 'SAVE_EXECUTION_SUCCEEDED',
  SAVE_EXECUTION_FAILED: 'SAVE_EXECUTION_FAILED',

  LOAD_RENDERING: 'LOAD_RENDERING',
  SET_RENDERING: 'SET_RENDERING',
  UPDATE_RENDERING: 'UPDATE_RENDERING',

  SAVE_RENDERING: 'SAVE_RENDERING',
  SAVE_RENDERING_SUCCEEDED: 'SAVE_RENDERING_SUCCEEDED',
  SAVE_RENDERING_FAILED: 'SAVE_RENDERING_FAILED',

  EDITOR_ACTION_ENABLED: 'EDITOR_ACTION_ENABLED',
  EDITOR_ACTION_DISABLED: 'EDITOR_ACTION_DISABLED',

  EDITOR_ACTION_VALID: 'EDITOR_ACTION_VALID',
  EDITOR_ACTION_INVALID: 'EDITOR_ACTION_INVALID',

  SET_ACTIVE_SCOPE: 'SET_ACTIVE_SCOPE',

  ENSURE_EDITOR_TITLE: 'ENSURE_EDITOR_TITLE',
};
