export const hikerExitReason = {
  none: 'none',
  dataError: 'dataError',
  renderError: 'renderError',
  trailMismatchError: 'trailMismatchError',
  hikeMismatchError: 'hikeMismatchError',
  otherError: 'otherError',
  noMovement: 'noMovement',
  exceededImageBounds: 'exceededImageBounds',
  exceededFabricBounds: 'exceededFabricBounds',
  blocked: 'blocked',
  exceededDataBounds: 'exceededDataBounds',
  reachedStepLimit: 'reachedStepLimit',
  hikerRule: 'hikerRule',
  reachedSimulationLimit: 'reachedSimulationLimit',
  simulationIdle: 'simulationIdle',
};
