import React from 'react';
import { makeImgUrl } from '../../../utils';
import * as styles from './styles.scss';

const img1 = makeImgUrl('DMEvenGen500.jpg');
const img2 = makeImgUrl('EveningCloudsDavisMountains500.jpg');
const img3 = makeImgUrl('EveSrcCut.jpg');
const img4 = makeImgUrl('DMEvenCut.png');

export default () => {
  return (
    <div>
      <p>
        Lens is a tool for “inferring” a new image from a photograph, with the "inference" performed via
        creative algorithms. The process begins with an analysis of the photograph, accumulating
        visual data that will be used as input into various simulations. One or more simulations are conducted,
        ranging from simple finite automata to more complex for creating emergent behavior. The results
        from the simulation are rendered as a new image.
      </p>
      <p>
        As a simple example, this photograph of a summer storm rolling through the Davis Mountains
        of west Texas was used as the input.
      </p>
      <img src={img2} alt='' className={styles.framedImage}/>
      <p>
        This "inferred" image was generated by applying a bin packing algorithm (simulation), driven by an
        analysis of the change in luminosity across the input photograph. The rendering applied
        a geometric ornamentation of concentric rings of shifted hues over measures of luminosity. Areas
        with low degrees of change created larger rings while high degrees of change generated smaller
        rings. By correlating ring size with the inverse rate of change, the spirit of the input photograph
        was preserved.
      </p>
      <img src={img1} alt=''
           className={styles.framedImage}/>
      <p>
        Here are full-resolution details taken from the input photograph and the corresponding
        region in the rendered image.
      </p>
      <div className={styles.cutContainer}>
        <div>
          <img src={img3} alt='' className={styles.framedImage}/>
        </div>
        <div>
          <img src={img4} alt='' className={styles.framedImage}/>
        </div>
      </div>
    </div>
  );
};
