export const ACTIONS = {
  REQUEST_CATALOG: 'REQUEST_CATALOG',
  RECEIVE_CATALOG: 'RECEIVE_CATALOG',
  REQUEST_CATALOG_FAILED: 'REQUEST_CATALOG_FAILED',

  REQUEST_IMAGE: 'REQUEST_IMAGE',
  CLEAR_REQUEST_IMAGE: 'CLEAR_REQUEST_IMAGE',
  RECEIVE_IMAGE: 'RECEIVE_IMAGE',

  REQUEST_STATS: 'REQUEST_STATS',
  CLEAR_REQUEST_STATS: 'CLEAR_REQUEST_STATS',
  RECEIVE_STATS: 'RECEIVE_STATS'
};

export const IMAGE_LIST_KEYS = {
  DEFAULT: 'images',
  THUMBNAILS: 'thumbnails'
};
